schemaVersion: 1
registry: 565090303272.dkr.ecr.us-east-1.amazonaws.com
region: us-east-1
runnerPublic:
  registryAlias: e1d5p6t0
  repository: runner
  uri: public.ecr.aws/e1d5p6t0/runner
  digest: sha256:12e430b202f5efabfe1d225ad7c8e224e320dd055a70afd9a9dd4e015b1113ab
publishedGitSha: c2c314ee3adbd74f73714a0d5ee2ed6c649192bf
publishedRunNumber: 516
publishedAt: 2026-06-16T23:25:43.760Z
components:
  api:
    ecrRepository: maxoperf/api
    tag: 537-29a26f8
  web:
    ecrRepository: maxoperf/web
    tag: 537-29a26f8
  marketing-site:
    ecrRepository: maxoperf/marketing-site
    tag: 537-29a26f8
  api-reference:
    ecrRepository: maxoperf/api-reference
    tag: 537-29a26f8
  runner-provisioning:
    ecrRepository: maxoperf/runner-provisioning
    tag: 538-e78bf0c
  outpost-agent:
    ecrRepository: maxoperf/outpost-agent
    tag: 537-29a26f8
  results-ingest:
    ecrRepository: maxoperf/results-ingest
    tag: 537-29a26f8
  results-processor:
    ecrRepository: maxoperf/results-processor
    tag: 537-29a26f8
  orchestration:
    ecrRepository: maxoperf/orchestration
    tag: 537-29a26f8
  run-orchestrator-worker:
    ecrRepository: maxoperf/run-orchestrator-worker
    tag: 537-29a26f8
  temporal-worker:
    ecrRepository: maxoperf/temporal-worker
    tag: 537-29a26f8
  mail-delivery:
    ecrRepository: maxoperf/mail-delivery
    tag: 537-29a26f8
  taurus-runner:
    ecrRepository: maxoperf/runner
    tag: 537-29a26f8
  keycloak:
    ecrRepository: maxoperf/keycloak
    tag: 537-29a26f8
  demo-shop:
    ecrRepository: maxoperf/demo-shop
    tag: 537-29a26f8
lambdaWriters:
  resultsLambdaWriter:
    function: maxoperf-staging-results-lambda-writer
    deployTag: 537-29a26f8
    codeSha256: 8Zqi5vDu/j//Gw/dkFa66XkVfkB7mHJeZtvDqGNZXXY=
    ciRunId: 27652066477
    publishedAt: 2026-06-16T22:57:09.506Z
