schemaVersion: 1
registry: 565090303272.dkr.ecr.us-east-1.amazonaws.com
region: us-east-1
runnerPublic:
  registryAlias: e1d5p6t0
  repository: runner
  uri: public.ecr.aws/e1d5p6t0/runner
  digest: sha256:12e430b202f5efabfe1d225ad7c8e224e320dd055a70afd9a9dd4e015b1113ab
publishedGitSha: 432b2260ed4bf5b653f953b5bb03889d41a21483
publishedRunNumber: 478
publishedAt: 2026-06-14T12:50:30.496Z
components:
  api:
    ecrRepository: maxoperf/api
    tag: 490-1c9e29f
  web:
    ecrRepository: maxoperf/web
    tag: 490-1c9e29f
  marketing-site:
    ecrRepository: maxoperf/marketing-site
    tag: 488-ec0d7ad
  runner-provisioning:
    ecrRepository: maxoperf/runner-provisioning
    tag: 490-1c9e29f
  outpost-agent:
    ecrRepository: maxoperf/outpost-agent
    tag: 488-ec0d7ad
  results-ingest:
    ecrRepository: maxoperf/results-ingest
    tag: 488-ec0d7ad
  results-processor:
    ecrRepository: maxoperf/results-processor
    tag: 488-ec0d7ad
  orchestration:
    ecrRepository: maxoperf/orchestration
    tag: 488-ec0d7ad
  run-orchestrator-worker:
    ecrRepository: maxoperf/run-orchestrator-worker
    tag: 488-ec0d7ad
  temporal-worker:
    ecrRepository: maxoperf/temporal-worker
    tag: 488-ec0d7ad
  mail-delivery:
    ecrRepository: maxoperf/mail-delivery
    tag: 488-ec0d7ad
  taurus-runner:
    ecrRepository: maxoperf/runner
    tag: 488-ec0d7ad
  keycloak:
    ecrRepository: maxoperf/keycloak
    tag: 488-ec0d7ad
lambdaWriters:
  resultsLambdaWriter:
    function: maxoperf-staging-results-lambda-writer
    deployTag: 488-ec0d7ad
    codeSha256: u80UdSpXVohbocTPjP0yp4DGUwsb5+WX1q9Y2njPFmw=
    ciRunId: 27487862314
    publishedAt: 2026-06-14T04:41:09.428Z
