schemaVersion: 1
registry: 565090303272.dkr.ecr.us-east-1.amazonaws.com
region: us-east-1
runnerPublic:
  registryAlias: e1d5p6t0
  repository: runner
  uri: public.ecr.aws/e1d5p6t0/runner
  digest: sha256:12e430b202f5efabfe1d225ad7c8e224e320dd055a70afd9a9dd4e015b1113ab
publishedGitSha: ddb5649e03c2eb9e0af437e8c655961761effad8
publishedRunNumber: 430
publishedAt: 2026-06-12T01:05:31.756Z
components:
  api:
    ecrRepository: maxoperf/api
    tag: 430-ddb5649
  web:
    ecrRepository: maxoperf/web
    tag: 430-ddb5649
  marketing-site:
    ecrRepository: maxoperf/marketing-site
    tag: 430-ddb5649
  runner-provisioning:
    ecrRepository: maxoperf/runner-provisioning
    tag: 451-a997ba6
  outpost-agent:
    ecrRepository: maxoperf/outpost-agent
    tag: 430-ddb5649
  results-ingest:
    ecrRepository: maxoperf/results-ingest
    tag: 430-ddb5649
  results-processor:
    ecrRepository: maxoperf/results-processor
    tag: 430-ddb5649
  orchestration:
    ecrRepository: maxoperf/orchestration
    tag: 430-ddb5649
  run-orchestrator-worker:
    ecrRepository: maxoperf/run-orchestrator-worker
    tag: 430-ddb5649
  temporal-worker:
    ecrRepository: maxoperf/temporal-worker
    tag: 430-ddb5649
  mail-delivery:
    ecrRepository: maxoperf/mail-delivery
    tag: 430-ddb5649
  taurus-runner:
    ecrRepository: maxoperf/runner
    tag: 430-ddb5649
  keycloak:
    ecrRepository: maxoperf/keycloak
    tag: 430-ddb5649
lambdaWriters:
  resultsLambdaWriter:
    function: maxoperf-staging-results-lambda-writer
    deployTag: 431-c0dd94c
    codeSha256: hklXxRP/p7Q8AiAK6+e6yU3+dLzrt4KDWAQzT23hZ6M=
    ciRunId: 27363439184
    publishedAt: 2026-06-11T17:30:59.173Z
